### ISSUE TITLE
I have No idea why this error .

### ISSUE THREAD

**Issue by shahid777-py** [fratajczak/one-monokai-vim#2]
Error detected while processing function <SNR>49_Hi[41]..<SNR>49_AddAnsiGroups:
line   18:
E15: Invalid expression: 'hi default CocList'.foreground.background.' guifg='.foregroundColor.' guibg='.backgroundColor
 I reallly like this colorschme .looking forward to stop that error.

![2020-12-06-193259_1920x1080_scrot](https://user-images.githubusercontent.com/56960053/101282285-4c83f480-37fa-11eb-9261-9b048e084623.png)

**Comment by fratajczak** [comment]
Thanks for the report, fixed in 4fdfd9347dac4a06ee5fb7c559c7e75424f74930.

**Comment by shahid777-py** [comment]
> Thanks for the report, fixed in [4fdfd93](https://github.com/fratajczak/one-monokai-vim/commit/4fdfd9347dac4a06ee5fb7c559c7e75424f74930).
Thanks, also i'm using multiple colorschemes with a keybind so i surressed that  with like  `nnoremap <C-m> : silent! colorscheme one-monokai`  i supressed with `silent!` , but ii still reported it maybe it hrlps other , bytheway your colorschme is cool and good nice try .
